FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel
#FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

#RUN apt-get update && apt install python3 install ffmpeg libsm6 libxext6 nvtop -y

# Set working directory
WORKDIR /app

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

# Copy the entire project
COPY . .

# Sync dependencies using uv
RUN uv sync --frozen

RUN pip install optimum[onnxruntime-gpu]

RUN uv pip install optimum[onnxruntime-gpu]

# Create Documents directory
RUN mkdir -p /api/Documents

# Expose the default port
#EXPOSE 8001

# Set environment variables
#ENV HOST=0.0.0.0
#ENV PORT=8001
ENV PYTHONUNBUFFERED=1

# Run the server
CMD ["uv", "run", "fetchcraft-docling-server"]
